### ISSUE TITLE
Vse huinya

### ISSUE THREAD

**Issue by alsmirnoff** [upperbound/disapp#1]
Davay po novoy

**Comment by Tsovak** [comment]
cannot reproduce

**Comment by AlexSmirnoff** [comment]
You motherfucker, come on you little ass… closed my issues, eh? You fucking little asshole, dickhead cocksucker…You fuckin' come on, close my issues! I'll close you by myself, you jerk!

**Comment by alsmirnoff** [comment]
Удалением комментариев нас не сломить. 
P.s.: Digital Resistance.
